name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build for multiple platforms
      run: |
        mkdir -p dist
        
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -o auto-pr .
        tar czf dist/auto-pr-linux-amd64.tar.gz auto-pr
        rm auto-pr
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -o auto-pr .
        tar czf dist/auto-pr-linux-arm64.tar.gz auto-pr
        rm auto-pr
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -o auto-pr .
        tar czf dist/auto-pr-darwin-amd64.tar.gz auto-pr
        rm auto-pr
        
        # macOS arm64
        GOOS=darwin GOARCH=arm64 go build -o auto-pr .
        tar czf dist/auto-pr-darwin-arm64.tar.gz auto-pr
        rm auto-pr
        
        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -o auto-pr.exe .
        tar czf dist/auto-pr-windows-amd64.tar.gz auto-pr.exe
        rm auto-pr.exe
        
        # Windows arm64
        GOOS=windows GOARCH=arm64 go build -o auto-pr.exe .
        tar czf dist/auto-pr-windows-arm64.tar.gz auto-pr.exe
        rm auto-pr.exe
    
    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
        generate_release_notes: true
        draft: false
        prerelease: false